const drinks=[
{id:'americano',name:'아메리카노',price:3500,color:'#b56f3a',temps:['hot','ice']},
{id:'latte',name:'카페라떼',price:4200,color:'#c69a6a',temps:['hot','ice']},
{id:'vanilla',name:'바닐라 라떼',price:4700,color:'#d9b777',temps:['hot','ice']},
{id:'green-tea',name:'녹차 라떼',price:4500,color:'#7fa36b',temps:['hot','ice']},
{id:'iced-tea',name:'아이스티',price:3800,color:'#d48a58',temps:['ice']},
{id:'chocolate',name:'초콜릿',price:4500,color:'#8b5e4d',temps:['hot','ice']}
];
const optionSteps=[{key:'temp',title:'따뜻하게 마실까요, 차갑게 마실까요?',short:'온도'},{key:'size',title:'어떤 크기로 주문할까요?',short:'크기'}];
const fieldLabels={drink:'음료',temp:'온도',size:'크기',place:'매장·포장'};
const state={stage:'start',drinkId:null,temp:null,size:null,place:null,optionStep:0,editingField:null,editSnapshot:null};
const app=document.querySelector('#app'),live=document.querySelector('#live-region');
const money=n=>`${n.toLocaleString('ko-KR')}원`,drink=()=>drinks.find(x=>x.id===state.drinkId)||null,total=()=>(drink()?.price||0)+(state.size==='large'?500:0);
const tempLabel=v=>v==='hot'?'따뜻하게 (HOT)':'차갑게 (ICE)',sizeLabel=v=>v==='large'?'라지':'레귤러',placeLabel=v=>v==='takeout'?'포장해서 가져가기':'매장에서 마시기';
const editing=k=>state.editingField===k;
function announce(t){live.textContent='';requestAnimationFrame(()=>live.textContent=t)}
function snapshot(){return{drinkId:state.drinkId,temp:state.temp,size:state.size,place:state.place}}
function reset(stage='start'){Object.assign(state,{stage,drinkId:null,temp:null,size:null,place:null,optionStep:0,editingField:null,editSnapshot:null})}
function progress(n){const ls=['음료','추가 선택','매장·포장','확인','완료'];return `<nav class="progress" aria-label="주문 진행 단계">${ls.map((x,i)=>{const k=i+1,s=k<n?'complete':k===n?'current':'upcoming',m=s==='complete'?'✓':k,a=s==='current'?', 현재 단계':s==='complete'?', 완료':'';return `<div class="progress-step ${s}" aria-label="${k}단계 ${x}${a}"><span class="step-circle" aria-hidden="true">${m}</span><span>${x}</span></div>`}).join('')}</nav>`}
const cue=t=>`<div class="task-cue"><span aria-hidden="true">→</span><strong>${t}</strong></div>`;
function editNotice(k){const t=k==='drink'?'수정 중 · 음료를 바꾸고 있어요. 크기와 매장·포장은 유지되고, 새 음료에 따라 온도는 바뀔 수 있어요.':`수정 중 · ${fieldLabels[k]}만 바꾸고 있어요. 다른 선택은 그대로 유지돼요.`;return `<div class="task-cue" role="status"><span aria-hidden="true">↩</span><strong>${t}</strong></div>`}
function summary(next=''){const d=drink();if(!d)return'';const rows=[['온도',state.temp?tempLabel(state.temp):'아직 선택하지 않았어요'],['크기',state.size?sizeLabel(state.size):'아직 선택하지 않았어요'],['매장·포장',state.place?placeLabel(state.place):'아직 선택하지 않았어요']];return `<aside class="screen-card summary-panel" aria-label="현재 주문 내용"><div class="summary-title-row"><h2>현재 주문</h2><span class="summary-count">1잔</span></div><div class="summary-drink"><span class="mini-drink-dot" style="--drink-color:${d.color}" aria-hidden="true"></span><div><strong>${d.name}</strong><br><span>${money(total())}</span></div></div><ul class="summary-list">${rows.map(([k,v])=>`<li class="${v.startsWith('아직')?'pending':''}"><span>${k}</span><strong>${v}</strong></li>`).join('')}</ul>${next?`<p class="summary-next"><span>다음</span><strong>${next}</strong></p>`:''}</aside>`}
function startView(){return `<section class="start-screen" aria-labelledby="page-title"><div class="screen-card start-panel"><div><p class="eyebrow">실제 카페처럼 한 단계씩</p><h1 id="page-title" tabindex="-1">카페 주문을 연습해 볼까요?</h1><p class="lead">고르고, 확인하고, 필요하면 바로 바꿀 수 있어요.</p><ol class="start-route" aria-label="연습 순서"><li><strong>1</strong><span>음료 고르기</span></li><li><strong>2</strong><span>온도·크기 고르기</span></li><li><strong>3</strong><span>매장·포장 고르기</span></li><li><strong>4</strong><span>확인하고 주문하기</span></li></ol><div class="start-actions"><button class="btn btn-primary btn-wide" type="button" data-action="start">연습 시작하기</button></div></div><div class="hero-visual" aria-hidden="true"><div class="cup hero-cup" style="--drink-color:var(--color-action-primary)"></div></div></div></section>`}
function drinkView(){const d=drink(),e=editing('drink'),impact=e&&state.editSnapshot?.temp&&state.temp!==state.editSnapshot.temp;return `${progress(e?4:1)}<section class="screen-card main-card" aria-labelledby="page-title"><div class="screen-head">${e?editNotice('drink'):''}<p class="eyebrow">${e?'4단계 · 주문 확인 · 음료 수정':'1단계 · 음료 선택'}</p><h1 id="page-title" tabindex="-1">${e?'어떤 음료로 바꿀까요?':'어떤 음료를 마실까요?'}</h1><p class="lead">마시고 싶은 음료 하나를 눌러 주세요.</p>${cue(d?`${d.name}를 골랐어요. ${impact?`${d.name}는 ${tempLabel(state.temp)}로 주문해야 해서 온도도 함께 바뀌었어요. `:''}${e?'이 선택으로 주문 확인에 돌아갈 수 있어요.':'아래의 ‘다음으로’ 버튼을 눌러요.'}`:'음료 하나를 골라요.')}</div><div class="drink-grid" role="group" aria-label="음료 메뉴">${drinks.map(x=>{const s=x.id===state.drinkId;return `<button class="drink-card ${s?'selected':''}" type="button" data-action="select-drink" data-id="${x.id}" aria-pressed="${s}" style="--drink-color:${x.color}">${s?'<span class="selected-badge">✓ 선택됨</span>':''}<span class="drink-visual" aria-hidden="true"><span class="cup"></span></span><span class="drink-name">${x.name}</span><span class="drink-price">${money(x.price)}</span></button>`}).join('')}</div></section><div class="action-bar"><div class="action-summary">${d?`<strong>${d.name}</strong><span>${e?'수정할 음료':'선택한 음료'}</span>`:'<strong>아직 고르지 않았어요</strong><span>위에서 음료 하나를 눌러 주세요</span>'}</div><div class="action-buttons">${e?'<button class="btn btn-secondary" type="button" data-action="cancel-edit">수정 취소</button>':''}<button class="btn btn-primary btn-wide" type="button" data-action="drink-next" ${d?'':'disabled'}>${e?'이 선택으로 돌아가기':'다음으로'}</button></div></div>`}
function tempChoices(d){if(d.temps.length===1)return `<div class="option-list"><button class="option-choice selected" type="button" data-action="select-option" data-key="temp" data-value="ice" aria-pressed="true">차갑게 (ICE)<span class="option-note">이 음료는 차갑게 주문해요.</span></button></div>`;return `<div class="option-list">${[['hot','따뜻하게 (HOT)','따뜻한 음료로 주문해요.'],['ice','차갑게 (ICE)','얼음이 들어간 음료로 주문해요.']].map(([v,l,n])=>`<button class="option-choice ${state.temp===v?'selected':''}" type="button" data-action="select-option" data-key="temp" data-value="${v}" aria-pressed="${state.temp===v}">${l}<span class="option-note">${n}</span></button>`).join('')}</div>`}
function sizeChoices(){return `<div class="option-list">${[['regular','레귤러','기본 크기'],['large','라지','조금 더 큰 크기 · +500원']].map(([v,l,n])=>`<button class="option-choice ${state.size===v?'selected':''}" type="button" data-action="select-option" data-key="size" data-value="${v}" aria-pressed="${state.size===v}">${l}<span class="option-note">${n}</span></button>`).join('')}</div>`}
const optionValue=()=>state[optionSteps[state.optionStep].key];
function optionsView(){const d=drink(),st=optionSteps[state.optionStep],e=editing(st.key),choices=st.key==='temp'?tempChoices(d):sizeChoices(),next=state.optionStep===1?'매장·포장 고르기':'다음으로';return `${progress(e?4:2)}<div class="option-layout"><section class="screen-card option-card" aria-labelledby="page-title">${e?editNotice(st.key):`<span class="option-substep">추가 선택 ${state.optionStep+1} / 2</span>`}<p class="eyebrow">${e?`4단계 · 주문 확인 · ${st.short} 수정`:'2단계 · 추가 선택'}</p><h1 id="page-title" tabindex="-1">${e?`${st.short}를 어떻게 바꿀까요?`:st.title}</h1><p class="lead">하나를 눌러 주세요. 고른 뒤에도 다시 바꿀 수 있어요.</p>${choices}${cue(optionValue()?`${st.short}를 골랐어요. ${e?'이 선택으로 주문 확인에 돌아갈 수 있어요.':'다음으로 가도 돼요.'}`:`${st.short}를 하나 골라요.`)}<div class="action-bar"><div class="action-summary"><strong>${optionValue()?'선택했어요':'하나를 골라 주세요'}</strong><span>${st.short} 선택</span></div><div class="action-buttons"><button class="btn btn-secondary" type="button" data-action="${e?'cancel-edit':'option-back'}">${e?'수정 취소':'이전으로'}</button><button class="btn btn-primary btn-wide" type="button" data-action="option-next" ${optionValue()?'':'disabled'}>${e?'이 선택으로 돌아가기':next}</button></div></div></section>${summary(e?'수정 후 주문 확인으로 돌아가기':state.optionStep===0?'크기 고르기':'매장·포장 고르기')}</div>`}
function placeView(){const e=editing('place');return `${progress(e?4:3)}<div class="option-layout"><section class="screen-card option-card" aria-labelledby="page-title">${e?editNotice('place'):''}<p class="eyebrow">${e?'4단계 · 주문 확인 · 매장·포장 수정':'3단계 · 매장·포장'}</p><h1 id="page-title" tabindex="-1">${e?'매장·포장을 어떻게 바꿀까요?':'어디에서 마실까요?'}</h1><p class="lead">실제 카페처럼 매장에서 마실지, 포장할지 골라요.</p><div class="option-list place-list" role="group" aria-label="매장 또는 포장 선택">${[['dinein','매장에서 마실게요','카페 안에서 마셔요.'],['takeout','포장해서 가져갈게요','음료를 가지고 나가요.']].map(([v,l,n])=>`<button class="option-choice ${state.place===v?'selected':''}" type="button" data-action="select-place" data-value="${v}" aria-pressed="${state.place===v}">${l}<span class="option-note">${n}</span></button>`).join('')}</div>${cue(state.place?`${placeLabel(state.place)}를 골랐어요. ${e?'이 선택으로 주문 확인에 돌아갈 수 있어요.':'주문 내용을 확인해요.'}`:'매장 또는 포장 중 하나를 골라요.')}<div class="action-bar"><div class="action-summary"><strong>${state.place?'선택했어요':'하나를 골라 주세요'}</strong><span>매장·포장 선택</span></div><div class="action-buttons"><button class="btn btn-secondary" type="button" data-action="${e?'cancel-edit':'place-back'}">${e?'수정 취소':'이전으로'}</button><button class="btn btn-primary btn-wide" type="button" data-action="place-next" ${state.place?'':'disabled'}>${e?'이 선택으로 돌아가기':'주문 확인하기'}</button></div></div></section>${summary(e?'수정 후 주문 확인으로 돌아가기':'주문 내용 확인하기')}</div>`}
function sentence(){const d=drink();if(!d||!state.temp||!state.size||!state.place)return'';return `${state.temp==='ice'?'아이스':'따뜻한'} ${d.name} ${sizeLabel(state.size)} 사이즈로 주세요. ${state.place==='takeout'?'포장해 주세요':'매장에서 마실게요'}.`}
const canReview=()=>Boolean(drink()&&state.temp&&state.size&&state.place);
const detail=(l,v,k)=>`<div class="review-detail-row"><div><span>${l}</span><strong>${v}</strong></div><button class="small-edit" type="button" data-action="edit-field" data-key="${k}" aria-label="${l} 바꾸기">바꾸기</button></div>`;
function reviewView(){const d=drink();return `${progress(4)}<div class="review-layout"><section class="screen-card review-card" aria-labelledby="page-title"><p class="eyebrow">4단계 · 주문 확인</p><h1 id="page-title" tabindex="-1">주문할 내용이 맞나요?</h1><p class="lead">다르면 옆의 ‘바꾸기’를 눌러 그 항목만 고칠 수 있어요.</p><div class="order-item"><span class="mini-drink-dot" style="--drink-color:${d.color}" aria-hidden="true"></span><div class="order-main"><strong>${d.name}</strong><span>음료 1잔</span></div><button class="small-edit" type="button" data-action="edit-field" data-key="drink" aria-label="음료 바꾸기">바꾸기</button></div><div class="review-detail-list" aria-label="주문 세부 내용">${detail('온도',tempLabel(state.temp),'temp')}${detail('크기',sizeLabel(state.size),'size')}${detail('매장·포장',placeLabel(state.place),'place')}</div><div class="practice-sentence"><span class="label">직원에게 이렇게 말해 볼 수 있어요</span><p>“${sentence()}”</p></div>${cue('모두 맞으면 ‘이대로 주문할게요’를 눌러요.')}</section><aside class="screen-card total-panel" aria-label="주문 합계"><span class="total-kicker">최종 확인</span><div class="total-line"><span>총 금액</span><strong>${money(total())}</strong></div><button class="btn btn-primary" type="button" data-action="complete-order">이대로 주문할게요</button><button class="btn btn-secondary" type="button" data-action="review-back">이전 단계로</button></aside></div>`}
function completeView(){const d=drink();return `${progress(5)}<section class="complete-screen" aria-labelledby="page-title"><div class="screen-card complete-card"><div class="complete-check" aria-hidden="true">✓</div><p class="eyebrow">5단계 · 완료</p><h1 id="page-title" tabindex="-1">주문 연습을 마쳤어요!</h1><p class="lead">주문이 완료되었어요. 내가 주문한 내용을 다시 볼 수 있어요.</p><div class="complete-order"><strong>${d.name} · ${sizeLabel(state.size)}</strong><span>${tempLabel(state.temp)} · ${placeLabel(state.place)}</span><span>${money(total())}</span></div><div class="practice-sentence"><span class="label">내가 연습한 주문 문장</span><p>“${sentence()}”</p></div><div class="complete-actions"><button class="btn btn-primary btn-wide" type="button" data-action="restart">다시 연습하기</button></div></div></section>`}
function render({focusTitle=true,focusSelector=null}={}){const views={start:startView,drink:drinkView,options:optionsView,place:placeView,review:reviewView,complete:completeView};app.innerHTML=views[state.stage]();requestAnimationFrame(()=>focusSelector?app.querySelector(focusSelector)?.focus():focusTitle&&app.querySelector('#page-title')?.focus())}
function chooseDrink(id){const d=drinks.find(x=>x.id===id);if(!d)return;state.drinkId=id;if(!d.temps.includes(state.temp))state.temp=d.temps.length===1?d.temps[0]:null;announce(`${d.name}를 선택했습니다.`);render({focusTitle:false,focusSelector:`[data-action="select-drink"][data-id="${id}"]`})}
function setOption(k,v){if(!['temp','size'].includes(k)||k==='temp'&&!drink()?.temps.includes(v))return;state[k]=v;announce(`${k==='temp'?tempLabel(v):sizeLabel(v)}를 선택했습니다.`);render({focusTitle:false,focusSelector:`[data-action="select-option"][data-key="${k}"][data-value="${v}"]`})}
function setPlace(v){if(!['dinein','takeout'].includes(v))return;state.place=v;announce(`${placeLabel(v)}를 선택했습니다.`);render({focusTitle:false,focusSelector:`[data-action="select-place"][data-value="${v}"]`})}
function editField(k){if(!fieldLabels[k])return;state.editSnapshot=snapshot();state.editingField=k;if(k==='drink')state.stage='drink';if(k==='temp')Object.assign(state,{stage:'options',optionStep:0});if(k==='size')Object.assign(state,{stage:'options',optionStep:1});if(k==='place')state.stage='place';announce(`${fieldLabels[k]}를 다시 선택할 수 있습니다.`);render()}
function finishEdit(){if(!state.editingField||!canReview())return;const l=fieldLabels[state.editingField];Object.assign(state,{stage:'review',editingField:null,editSnapshot:null});announce(`${l} 수정을 마쳤습니다. 주문 내용을 다시 확인합니다.`);render()}
function cancelEdit(){if(!state.editingField)return;const l=fieldLabels[state.editingField];Object.assign(state,state.editSnapshot,{stage:'review',editingField:null,editSnapshot:null});announce(`${l} 수정을 취소했습니다. 원래 주문 내용을 유지합니다.`);render()}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
if(a==='start'){state.stage='drink';announce('음료를 고르는 1단계를 시작합니다.');return render()}
if(a==='select-drink')return chooseDrink(b.dataset.id);if(a==='cancel-edit')return cancelEdit();
if(a==='drink-next'&&state.drinkId){if(editing('drink'))return finishEdit();Object.assign(state,{stage:'options',optionStep:0});if(drink().temps.length===1)state.temp=drink().temps[0];announce('온도와 크기를 고르는 2단계입니다.');return render()}
if(a==='select-option')return setOption(b.dataset.key,b.dataset.value);
if(a==='option-back'){if(state.optionStep>0)state.optionStep--;else state.stage='drink';announce('이전 선택으로 돌아갑니다.');return render()}
if(a==='option-next'&&optionValue()){if(editing(optionSteps[state.optionStep].key))return finishEdit();if(state.optionStep<1){state.optionStep++;announce('크기를 고르는 단계입니다.')}else{state.stage='place';announce('매장 또는 포장을 고르는 3단계입니다.')}return render()}
if(a==='select-place')return setPlace(b.dataset.value);
if(a==='place-back'){Object.assign(state,{stage:'options',optionStep:1});announce('크기 선택으로 돌아갑니다.');return render()}
if(a==='place-next'&&state.place){if(editing('place'))return finishEdit();state.stage='review';announce('주문 내용을 확인하는 4단계입니다.');return render()}
if(a==='edit-field')return editField(b.dataset.key);
if(a==='review-back'){state.stage='place';announce('매장 또는 포장 선택으로 돌아갑니다.');return render()}
if(a==='complete-order'&&canReview()){state.stage='complete';announce('주문 연습이 완료되었습니다.');return render()}
if(a==='restart'){reset('drink');announce('새 주문 연습을 시작합니다. 음료를 골라 주세요.');return render()}
});
render();
